repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.0
    hooks:
      # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
    -   id: nbstripout
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.31.1
    hooks:
      - id: cspell
