name: linting

on: [push]

env:
  UV_SYSTEM_PYTHON: true

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install package and dev dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install ".[dev]"
      - name: ruff check
        run: |
          ruff check src/pynxtools_igor tests
      - name: ruff format
        if: ${{ always() }}
        run: |
          ruff format --check src/pynxtools_igor tests
      - name: mypy
        if: ${{ always() }}
        run: |
          mypy src/pynxtools_igor tests
      - name: spellcheck
        if: ${{ always() }}
        uses: streetsidesoftware/cspell-action@v6
        with:
          check_dot_files: false
          incremental_files_only: false
          config: './cspell.json'
